### ISSUE TITLE
Possible security vulnerability when multiple values passed in expectedScopes

### ISSUE THREAD

**Issue by saulimus** [auth0/express-jwt-authz#1]
## Description
If an endpoint requires multiple scopes (expectedScopes.length > 1), then it is possible to gain access if the user has only one of the required scopes.
This is because this piece of code only checks if **some** of the expected scopes match:
`
var allowed = expectedScopes.some(function(scope){
                return scopes.indexOf(scope) !== -1;
            });
`

## Example
If a user has scopes ['read:something'] and expected scopes are ['read:something', 'write:something'], user will be able to access the endpoint.

**Comment by Irrelon** [comment]
Surely this is correct behaviour though? Since the scopes should be a logical OR not an AND.

**Comment by saulimus** [comment]
Then that should be documented and not implied.

**Comment by Irrelon** [comment]
@saulimus Makes sense. Would you like to put in a PR for the updated doc?

**Comment by akehir** [comment]
Actually, [this](https://github.com/MichielDeMey/express-jwt-permissions) library uses arrays of arrays of strings for the logical AND, and arrays of strings for a logical OR.

```javascript
// Required: "read" OR "write"
app.use(guard.check([
  ['read'],
  ['write']
]))

// Required: "admin" OR ("read" AND "write")
app.use(guard.check([
  ['admin'],
  ['read', 'write']
]))
```

To me, it makes sense to have both options.

**Comment by akehir** [comment]
Actually, I just realized, one can just verify multiple scopes like this:
```
// create retrieve endpoint endpoint
app.get('/endpoint', checkJwt, jwtAuthz(['READ']), jwtAuthz(['WRITE']), function (req, res) {
  // code that retrieves the user's balance and sends it back to the calling app

  res.status(201).send({message: "{\"message\": \"This is the GET /endpoint endpoint\""});
});
```

Therefore probably it's ok to leave the implementation as is, and update the documentation.
