### ISSUE TITLE
req.user.scope can be an array

### ISSUE THREAD

**Issue by brandonrutledge** [auth0/express-jwt-authz#14]
https://github.com/auth0/express-jwt-authz/blob/78a1ed6cddd4aee320ea943aa84fb1d96dfda63a/lib/index.js#L14

Is multiple scopes are defined, express-jwt@5.3.1 returns a string array and not a space delimited string.

**Comment by boyander** [comment]
I'm with @brandonrutledge `express-jwt` returns an array for tokens, check before split to avoid errors

**Comment by deammer** [comment]
This will be fixed by #15.
