### ISSUE TITLE
res.send args are deprecated

### ISSUE THREAD

**Issue by calmcl1** [auth0/express-jwt-authz#16]
If the user scopes are not sufficient to access the resource, the `error` function uses 

```return res.send(401, 'Insufficient scope');``` to complete the Express response.

However, this style is now deprecated; Express reports the following on the console:

```express deprecated res.send(status, body): Use res.status(status).send(body) instead at node_modules\express-jwt-authz\lib\index.js:2:14```

Suggest replacing the on-`error` function with:

``` 
return res.status(401).send('Insufficient scope');
```
before this breaks.

**Comment by expatiating** [comment]
@calmcl1 it appears this is fixed in master.
https://github.com/auth0/express-jwt-authz/blob/78a1ed6cddd4aee320ea943aa84fb1d96dfda63a/lib/index.js#L1

@luisrudge & @dschenkelman are you ready to publish on NPM?

**Comment by luisrudge** [comment]
fixed in #12
