### ISSUE TITLE
Option to bubble error instead of returning the response directly

### ISSUE THREAD

**Issue by eugeniop** [auth0/express-jwt-authz#17]
Curious why here:
https://github.com/auth0/express-jwt-authz/blob/master/lib/index.js#L15
and here:
https://github.com/auth0/express-jwt-authz/blob/master/lib/index.js#L20

you are not bubbling the error through `next(...)` and allow Express to deal with the error.

**Comment by luisrudge** [comment]
We want to return specific status codes instead of just throwing an error. We're following [this](https://expressjs.com/en/guide/error-handling.html) guide's best practices.

**Comment by luisrudge** [comment]
Would an option like this make sense? 

https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L171-L173

```js
if (options.failWithError) {
  return next(new AuthenticationError(msg, status));
}
```

**Comment by yliaho** [comment]
@luisrudge That's how I expected it to work when I want something to `failWithError` 😄 
Was quite confused by this as well.

**Comment by luisrudge** [comment]
I forgot to close this issue, but we already have this implemented (and another few options): https://github.com/auth0/express-jwt-authz#options

**Comment by yliaho** [comment]
@luisrudge But why not give an actual Error instead?

**Comment by luisrudge** [comment]
what do you mean by 'an actual Error'?

**Comment by luisrudge** [comment]
Oh, you mean the Error Object?

**Comment by yliaho** [comment]
That's right! :)

**Comment by luisrudge** [comment]
I don't know why it wasn't like this in the first place, but I guess it was simpler to just fail with an object etc.

**Comment by yliaho** [comment]
I think I see what you mean by "simpler", but it was rather confusing having a string representation of an object printed on the terminal when I just wanted to have a quick feedback why my scopes aren't working.

**Comment by luisrudge** [comment]
I can see why this is annoying. Do you want to send a PR that converts our objects to an error? It's imperative that they keep the same properties accessible though (`statusCode`, `error`, `message`)

**Comment by yliaho** [comment]
#24
