### ISSUE TITLE
No types for express-jwt-authz

### ISSUE THREAD

**Issue by jabney** [auth0/express-jwt-authz#25]
I couldn't find any types for this module, i.e., `npm install @types/express-jtw-authz`.

This declaration code (`index.d.ts`) works either side-by-side with `lib/index.js` in the `node_modules/express-jwt-authz` folder (v2.3.1), or manually placed in `node_modules/@types/express-jwt-authz`.

`index.d.ts`:

```typescript
import { Request, Response, NextFunction } from 'express';

declare global {
    namespace Express {
        interface Request {
            user: any;
        }
    }
}

export interface IAuthzOptions {
    failWithError: boolean;
    checkAllScopes: boolean;
    customScopeKey: string;
}

export default function(expectedScopes: string[], options?: IAuthzOptions): (req: Request, res: Response, next: NextFunction) => void;
```

**Comment by luisrudge** [comment]
Thanks! We don't offer OOTB types, but feel free to submit this file to https://github.com/DefinitelyTyped/DefinitelyTyped so others can benefit as well. 🎉
