### ISSUE TITLE
Misleading/incorrect documentation

### ISSUE THREAD

**Issue by adrianroworth** [auth0/express-jwt-authz#26]
The documentation contains the following:

---
If multiple scopes are provided, the user must have _any_ the required scopes.

```javascript
app.post('/users',
  jwt({ secret: 'shared_secret' }),
  jwtAuthz([ 'read:users', 'write:users' ], {}),
  function(req, res) { ... });

// This user will be denied access
var authorizedUser = {
  scope: 'read:users'
};
```
---
I believe the inline comment is incorrect and should be changed to:

```javascript
// This user will be granted access
```

Am I understanding how this module is intended to behave? Is this indeed an error in the documentation?

**Comment by armoj** [comment]
a better wording would be:

```javascript
// This user will be granted access
```

**Comment by adrianroworth** [comment]
A better wording would be:
```javascript
// This user will be granted access
```

**Comment by adrianroworth** [comment]
PR created for this: #27

**Comment by aarongodin** [comment]
Good catch. I've merged the PR, so I'll close this issue.
