### ISSUE TITLE
Add Typescript Support

### ISSUE THREAD

**Issue by jake-wickstrom** [auth0/express-jwt-authz#28]
### Describe the problem you'd like to have solved

Currently, there is no .d.ts file for this module, meaning it does not play well with typescript projects. 

### Describe the ideal solution

Add a .d.ts file to this module or create a @types/express-jwt-authz module to allow typescript projects to intelligently use this module

## Alternatives and current work-arounds

Currently, I am requiring the library as a plain JS module

**Comment by jake-wickstrom** [comment]
Created PR #29 to address this

**Comment by rplusg** [comment]
Hi, is there is any work around for this issue:

src/server.ts:4:22 - error TS7016: Could not find a declaration file for module 'express-jwt-authz'. 'C:/Code/Nodejs_practice/nodeHttp/node_modules/express-jwt-authz/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/express-jwt-authz` if it exists or add a new declaration (.d.ts) file containing `declare module 'express-jwt-authz';`

4 import jwtAuthz from 'express-jwt-authz';

Im on express-jwt-authz 2.3.1 version(taken from package json)

**Comment by jake-wickstrom** [comment]
Version 2.3.1 does not include the type declarations

One potential (temporary) workaround would be to use the master branch directly as your dependency rather than going through the latest version published to npm

npm install --save auth0/express-jwt-authz#master

You can also include the typings directly in the typings directory of your project until this a new version of this package is published to npm

**Comment by fmozaffari** [comment]
@jake-wickstrom-lb  thanks for the workaround. Any Eta on when the typings will become available?

**Comment by SayakMukhopadhyay** [comment]
Yeah, a long time has gone since this was pushed to master but no release to NPM. There are #32 #34 #35 lying around. Can this be please pushed to NPM?
