### ISSUE TITLE
Error handling in express routes 

### ISSUE THREAD

**Issue by dibishks** [auth0/express-jwt-authz#30]
I am using 'express-jwt-authz' to validate the scope of a jwt token, I implemented the flow like below. Here when I am calling 'checkScopes' function from my routes but it will never return the result, the callback of 'jwtAuthz' is not throwing any success or error condition. How to check error handling in 'express-jwt-authz' auth npm.

```
Middleware 

    validation.js 

    const jwt = require('express-jwt');
    const jwtAuthz = require('express-jwt-authz');
    const jwksRsa = require('jwks-rsa');
    const config = require('../config/config');
    module.exports.checkScopes = function(options) {
      return function(req, res, next) {
        jwtAuthz(options, {customScopeKey: 'http://user.com/scopes'}, function(error) {
          if (error) {
            console.log('error', error)
          } else {
            console.log('result never called')
            next();
          }
        })
      }
    }

Routes 
    invitation.js 

    const express = require('express');
    const router = express.Router();
    const jwtValidation = require('../middleware/jwtValidation');
    router.get('/', jwtValidation.checkScopes([ 'create:users' ]), invitation.getAllInvitation);
```

**Comment by joshcanhelp** [comment]
@dibishks - Have you tried using as a middleware directly, as explained in the README?

https://github.com/auth0/express-jwt-authz#usage

I'm also seeing that you're pulling in `express-jwt` but not using it. You'll want to verify the token first before checking the scopes.
