### ISSUE TITLE
403 or 401?

### ISSUE THREAD

**Issue by donavon** [auth0/express-jwt-authz#36]
[The documentation](https://auth0.com/docs/quickstart/backend/nodejs#validate-access-tokens) on the website reads:

> The checkJwt middleware shown above checks if the user's Access Token included in the request is valid. If the token is not valid, the user gets a **401 Authorization** error when they try to access the endpoints.

But the code is sending a 403.

Edit 403 is correct. The docs are wrong.
~Which one is the correct thing to send? I would think 401 with a `WWW-Authenticate` header.~

**Comment by adamjmcgrath** [comment]
Hi @donavon - thanks for raising an issue

`checkJwt` refers to the `express-jwt` Middleware which checks if the JWT is valid and raises a 401 if it's not https://github.com/auth0/express-jwt/blob/master/lib/errors/UnauthorizedError.js#L7 so the documentation is correct
