### ISSUE TITLE
Make Typescript Play Nicely with JWT-Authz

### ISSUE THREAD

**Issue by written-fresh** [auth0/express-jwt-authz#46]
### Describe the problem you'd like to have solved

Does anyone know a clean way to handle typescript with this library. Not super versed in typescript and its nuances. Was wondering how I could cleanly implement a route with this library that I don't have to give my own custom type to the req param.

### Describe the ideal solution
If I have: 
```
router.get("/", checkJWT, jwtAuthz(...), (req, res) => {
    console.log(req.user) //<--- here is where I normally get an issue because user doesn't exist on the req object.
})
```

I wouldn't need to clarify that the req object has a type. Again, not sure if this is possible for the library or if it NEEDS to be on my end

## Alternatives and current work-arounds

The current workaround I have is to just extend the express.request interface like so:

```
export interface AuthenticatedRequest extends Request {
  user?: string;
}
```
Then in my endpoint I would :

```
router.get(
  "/",
  checkJWT,
  jwtAuthz(...),
  async (req: AuthenticatedRequest, res) => {
})
```

### Additional context
Again, if there is a way to implement this through the jwt library, that would be great.

Thanks

**Comment by adamjmcgrath** [comment]
Hi @drewhoffer - we don't know what type your user will be, so extending the express request interface yourself is the way to go:

```js
declare namespace Express {
    export interface Request {
        user: MyUser;
    }
}
```

**Comment by adamjmcgrath** [comment]
Also, this SDK should be used with `express-jwt` which will do this for you https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-jwt/index.d.ts#L66

**Comment by adamjmcgrath** [comment]
Closing - feel free to ping me if you'd like to reopen

**Comment by written-fresh** [comment]
Awesome man, thanks for the quick response on this @adamjmcgrath. This answer is exactly what I was looking for.
